### ISSUE TITLE
Molsketch installation failed

### ISSUE THREAD

**Issue by Chris959** [gmrandazzo/homebrew-gmr#2]
Hi,

Sorry to bother you. I updated my system to macOS High Sierra, and I found the installation of Molsketch failed, the error message was as below:

------------------------------------------------------

==> Installing molsketch from gmrandazzo/gmr
==> Downloading https://downloads.sourceforge.net/project/molsketch/Molsketch/Be
Already downloaded: /Users/apple/Library/Caches/Homebrew/molsketch-0.4.0.tar.gz
==> Patching
patching file CMakeLists.txt
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -D
==> make
==> make install
Last 15 lines from /Users/apple/Library/Logs/Homebrew/molsketch/03.make:
**make[1]: Nothing to be done for `preinstall'**.
Install the project...
/usr/local/Cellar/cmake/3.9.4_1/bin/cmake -P cmake_install.cmake
-- Install configuration: "Debug"
-- Installing: /usr/local/lib/libmolsketch-qt5.0.4.0.dylib
**CMake Error at libmolsketch/src/cmake_install.cmake:39 (file):
  file INSTALL cannot copy file
  "/tmp/molsketch-20171104-16976-9ytogd/Molsketch-0.4.0/build/libmolsketch/src/libmolsketch-qt5.0.4.0.dylib"
  to "/usr/local/lib/libmolsketch-qt5.0.4.0.dylib".**
Call Stack (most recent call first):
  libmolsketch/cmake_install.cmake:32 (include)
  cmake_install.cmake:32 (include)

make: *** [install] Error 1

--------------------------------------------------

Could you please tell me how to fix it? I installed Molsketch on the mac with previous macOS version, and it works fine. I don't know why the installation failed now, please help me.

Thank you very much.

Regards,
Chris

**Comment by gmrandazzo** [comment]
Dear Chris,

thanks for your bug report.
Now the molsketch compilation/installation should be fine. 
I have upgraded version from 0.4 to 0.5.

Best regards

**Comment by Chris959** [comment]
Dear Gmrandazzo,

Thank you so much for your quick fixing!

Regards,
Chris
